pipeline {
  agent any
  environment {
    dockerhub_username = '<dockerhub_username>'
    img_name = 'angular-hello'
    img_tag = sh (returnStdout: true, script: 'git log -1 --pretty=%h').trim()
    username = '<username>'
  }
  stages {
    stage('Build') {
      steps {
        sh """
          cd employee-management/
          docker build . -t ${dockerhub_username}/${img_name}:${img_tag}
        """
      }
    }
    stage('Push') {
      steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: '<username>', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
          sh """
            echo ${WORKSPACE}
            docker login -u ${USERNAME} -p ${PASSWORD}
            docker push ${dockerhub_username}/${img_name}:${img_tag}
            docker logout
          """
        }
      }
    }
//    stage('Deploy') {
//      steps {
//        sh """
//          cd employee-management/
//          helm upgrade --wait --install -f ${username}-frontend.yaml --set image.tag=${img_tag} --namespace ${username} --tiller-namespace ${username} ${username}-employee-management-frontend ../../kubemania/employee-management-frontend/
//        """
      }
    }
  }
}
