def dockerhub_username = 'depauna'
def img_name = 'angular-hello'
def img_tag = env.BUILD_NUMBER
def namespace = 'depauna'

pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh """
          cd employee-management/
          docker build . -t ${dockerhub_username}/${img_name}:${img_tag}
        """
      }
    }
    stage('Push') {
      steps {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'depauna', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
          sh """
            echo ${WORKSPACE}
            docker login -u ${USERNAME} -p ${PASSWORD}
            docker push ${dockerhub_username}/${img_name}:${img_tag}
            docker logout
          """
        }
      }
    }
    stage('Deploy') {
      steps {
        sh """
          cd employee-management/
          helm upgrade --wait --install -f user30-frontend.yaml --namespace user30 --tiller-namespace user30 user30-employee-management-frontend ../../kubemania/employee-management-frontend/
        """
      }
    }
  }
}
